name: msdo-main-pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: 'main'
    secrets:
      GH_TOKEN:
        required: false

jobs:
  msdo-dynamic-scanning:
    uses: ./.github/workflows/msdo-dynamic-scanning.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    with:
      branch: ${{ inputs.branch }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret-scan-credscan:
    uses: ./.github/workflows/msdo-credscan.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: msdo-dynamic-scanning
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret-scan-trufflehog:
    uses: ./.github/workflows/msdo-trufflehog.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-credscan
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret-scan-gitleaks:
    uses: ./.github/workflows/msdo-gitleaks.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-trufflehog
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
