name: Upload SARIF
description: Upload SARIF to GitHub Code Scanning
inputs:
  sarif_file:
    description: "Path to the SARIF file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload SARIF
      shell: bash
      run: |
        echo "Uploading SARIF file: ${{ inputs.sarif_file }}"
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/code-scanning/sarifs \
          -f commit_sha="${{ github.sha }}" \
          -f ref="${{ github.ref }}" \
          -f sarif="$(gzip -c '${{ inputs.sarif_file }}' | base64 -w 0)" \
          -f checkout_uri="https://github.com/${{ github.repository }}" \
          -f tool_name="MSDO"
