name: msdo-main-pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  msdo-core-scan:
    uses: ./.github/workflows/msdo-reusable.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    with:
      branch: main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret-scan-credscan:
    uses: ./.github/workflows/msdo-secret-scanning.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: msdo-core-scan

  secret-scan-trufflehog:
    uses: ./.github/workflows/msdo-trufflehog.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-credscan

  secret-scan-gitleaks:
    uses: ./.github/workflows/msdo-trufflehog.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-trufflehog
