name: msdo-secret-scanning

on:
  workflow_call:
  workflow_dispatch:

jobs:
  secret-scan:
    name: MSDO Secret Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.ref_name }}

      - name: Set tool to only run secret scan
        run: echo "TOOLS=credscan" >> $GITHUB_ENV

      - name: Install .NET 6 SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 6.0.415 --install-dir "$HOME/dotnet"
          echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
          echo "$HOME/dotnet" >> $GITHUB_PATH     

      - name: Run Microsoft Security DevOps - Secret Scan
        uses: theangrytech-git/security-devops-action@main
        id: msdo
        with:
          tools: ${{ env.TOOLS }}

      - name: Upload alerts to GitHub code scanning
        if: github.repository_visibility == 'public'
        uses: ./.github/actions/upload-sarif
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
